### ISSUE TITLE
[Question]: Navigating link issue on readme

### ISSUE THREAD

**Issue by msv96** [IBMa/equal-access#1047]
### Project

cypress accessibility checker

### Description

Link on cypress-accessibility-checker navigates to accessibility-checker.

**Comment by tombrunet** [comment]
Is this in regards to this sentence?
> This plugin is a Cypress flavor of the NodeJS version of accessibility-checker which is also [available on NPM](https://www.npmjs.com/package/accessibility-checker).

The README is intended for NPM: https://www.npmjs.com/package/cypress-accessibility-checker . In this context, it's discussing the accessibility-checker, and therefore providing a link to the other tool (assuming you're already on the NPM page for this tool).

**Comment by srini-leanfolks** [comment]
Yes

**Comment by aliunwala** [comment]
Triage:
@philljenkins @mbgower We think this okay since this sentence
This plugin is a Cypress flavor of the NodeJS version of accessibility-checker which is also [available on NPM](https://www.npmjs.com/package/accessibility-checker).

Is not hosted on the repo its is hosted on the NPM site. Wanted to get a second pair of eyes to confirm that looks okay to you.
