### ISSUE TITLE
[A11y_Bug]: IBM equal access chrome extension and npm package for accessibility-checker is not giving same result.

### ISSUE THREAD

**Issue by ShrutiP26** [IBMa/equal-access#1148]
### Project

a11y checker

### Browser

Chrome

### Operating System

Windows

### Automated testing tool and ruleset

IBM Access Accessibility Checker - latest deployment

### Assistive technology

No

### Description

The result from npm package command - npx achecker  --outputFolder C:\Users\s.hemant.patrikar\AAWorkspace\ibmreports  --outputFormat html "https://www.msn.com/en-in" is different from chrome extension IBM Accessibility checker

Result from npm package: 
<img width="704" alt="npm_package_result" src="https://user-images.githubusercontent.com/72301443/200752513-c50bcbeb-24de-431f-ad67-3d9b61349b93.png">

Result of chrome extension:
<img width="963" alt="chrome_ext_result" src="https://user-images.githubusercontent.com/72301443/200752893-2798669b-2f98-4b56-aa19-34557120a345.png">

### Steps to reproduce

Run the npx achecker command and check the result with chrome extension result for https://www.msn.com/en-in site.

**Comment by tombrunet** [comment]
The engine is the same, so given the same DOM, you will get the same results. What this means is that your two scenarios have different DOMs, which is an issue with not having identical test environments rather than anything to do with the tools.

I'd suggest going to the Elements tab and looking at the Accessibility Checker side panel and looking at the DOM nodes that are triggering and figure out why that part of the DOM loads differently. Typically, these reports crop up because the page loads differently due to different test environments (different page width, browser extensions that inject/modify content, etc).

**Comment by ShrutiP26** [comment]
Thanks @tombrunet

**Comment by aliunwala** [comment]
From Triage meeting:
Closing this issue for now. @ShrutiP26 If you have any additional issues free free to reopen this issue. And provide us a copy of both DOMs that you are running against so we can help debug.
