### ISSUE TITLE
Evaluate low risk hidden items

### ISSUE THREAD

**Issue by DavidMacDonald** [IBMa/equal-access#12]
I bet there is a certain group of common  elements that REACT **_would not_** populate. For instance, I doubt it would inject or mess with the following:

1. ALT text in an image
2. aria-* tokens
3. ```<label for>``` and form field combinations
4. ids referenced by aria-labelledby, describedby, aria-controls, aria-errormessage, 
5. etc...

I think there are a number of things that could be safely evaluated when they are hidden. It would be great to have that setting to evaluate hidden content back... and just leave out high risk elements such as:

-  ```<a ...></a>``` (commonly injected by REACT)
- empty ```<div>``` or ```<span>``` elements
- etc...

when the setting is set to check hidden content.

**Comment by tombrunet** [comment]
React itself does not specify what gets injected in the DOM - it just manages how it gets there and how state is managed. React itself runs in the Javascript sandbox, so nothing from React itself should show up in a DOM, unless you tell it to put it there.

Most of your statements, I can believe might be artifacts of a specific React UI toolkit, but those aren't properties of React itself. My experience is that there are a lot of UI toolkits out there that do strange, non-standard things, and often implement accessibility incorrectly.

Because of these issues, we have been working with the IBM Carbon team on their open source UI toolkit - https://www.carbondesignsystem.com/ - which does make an effort to support all of the accessibility aspects that you mention.

I'll leave this open to re-think through the hidden content feature, but our experience is that these days that kind of checking is less accurate, and generally misunderstood, which leads to more accessibility problems in the long run rather than fewer.

**Comment by tombrunet** [comment]
I have seen instances of most of what you label as 'safe'. For instance, alt can be populated based on locale, so the initial value can be an NLS code and then replaced with an on-demand loaded NLS string before it is shown. It may also be a hidden tracker token. The net is, if it's not displayed, it's not intended for a user, and there are no accessibility requirements for those items.
