### ISSUE TITLE
Minimum button size recommendation

### ISSUE THREAD

**Issue by arinclementibm** [IBMa/equal-access#121]
I'd like to request the Accessibility Checker to make recommendations to meet the 44x44 recommended (AAA) button size.

**Comment by tombrunet** [comment]
We will discuss. Our guidance and support are all based on WCAG 2.1 AA. But, we do recognize that larger targets will be helpful. Since we're dealing with restricted space and a lot of information, 44x44 targets for everything in the UI may not be feasible, but we'll have our designers look at what we can do.

**Comment by zhenwan** [comment]
@arinclementibm Talked with Checker's design team, They will consider using bigger button size in future release. Thanks for this recommendation.
