### ISSUE TITLE
[BUG]: Changing the rule date during storing scans can be bypass 

### ISSUE THREAD

**Issue by ErickRenteria** [IBMa/equal-access#1599]
### Project

a11y checker extension

### Browser

Chrome

### Description

If the user is storing scan and changes the date, a pop will come up letting them know that stored scan will deleted. If the user select cancel then saves it will keep original scans and continue storing scan with new rule date selected.
<img width="1002" alt="Screenshot 2023-08-25 at 3 03 26 PM" src="https://github.com/IBMa/equal-access/assets/62436670/6b74a24e-502a-4fe6-82a0-fc4a492eb76c">

### Steps to reproduce

1. Start storing scans in the checker. 
2. Go to settings and change the rule date 
3. select cancel 
4. select save 
User will by pass the fictionality

**Comment by shunguoy** [comment]
triage: Josiah is working on this.

**Comment by drjoho** [comment]
If cancel need to set the change in deployment date or guidelines back to the active ones.
DONE! and set to test.

@drjoho

 
Leave a comment
No file chosen
Attach files by dragging & dropping, selecting or pasting them.
Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/IBMa/equal-access/blob/69f4574fde5afdcf758df0f419d82c8b2d01df94/CONTRIBUTING.md) and [code of conduct](https://github.com/IBMa/equal-access/blob/69f4574fde5afdcf758df0f419d82c8b2d01df94/CODE_OF_CONDUCT.md).
Pipelines
E
Equal-Access
Test

Assignees
ErickRenteria
ErickRenteria
drjoho
drjoho
Labels
[Bug](https://github.com/IBMa/equal-access/labels/Bug)
[development](https://github.com/IBMa/equal-access/labels/development)
[extension-checker](https://github.com/IBMa/equal-access/labels/extension-checker)
[priority-3 (low)](https://github.com/IBMa/equal-access/labels/priority-3%20%28low%29)
Projects
None yet

Sprints
S5: Aug 3 - Aug 9, 2023
S6: Aug 10 - Aug 16, 2023
S7: Aug 17 - Aug 23, 2023
S8: Aug 24 - Aug 30, 2023
Milestone
No milestone

Estimate
5

Epics
[R5.3 Checker Extension work](https://github.com/IBMa/equal-access/issues/1516)

Releases
R5.3 - Summer Release
Development
Successfully merging a pull request may close this issue.

https://github.com/IBMa/equal-access/pull/1589
[IBMa/equal-access](https://github.com/IBMa/equal-access)
Notifications
Customize
You’re receiving notifications because you were mentioned.
5 participants
@aliunwala
@tombrunet
@MHoov
@ErickRenteria
@drjoho

**Comment by ErickRenteria** [comment]
@drjoho What is the expected action when user changes the guidelines? 
At this time the user can change the guidelines and the report will show all stored scans with the last guidelines selected. 
Example: User scan 1-3 scans with guidelines: IBM_Accessibility but if the y change the guidelines to scan 3 more pages the report will have a total of 6 scans with the newer guidelines selected. 

Suggestions: We should apply the delete reports if user changes the guiles similar to changing the rules dates.

**Comment by ErickRenteria** [comment]
Validated
