### ISSUE TITLE
[BUG]: install failing due to chrome driver and out of date lock files

### ISSUE THREAD

**Issue by davidmenendez** [IBMa/equal-access#1851]
### Project

accessibility-checker-extension

### Browser

Chrome

### Operating system

MacOS

### Description

in a recent update to `chromedriver` the URL for their CDN changed. This was fixed in `v122.0.1`

this repo appears to be using `*` in `package.json` for `chromedriver`. i'd recommend setting a specific version of that and also updating the lock files because currently they are pointing to `v119`

### Steps to reproduce

`npm i`

**Comment by tombrunet** [comment]
We have a `.npmrc` with `detect_chromedriver_version=true`. This aligns chromedriver to the version of Chrome that you are using locally. See https://www.npmjs.com/package/chromedriver#detect-chromedriver-version

**Comment by tombrunet** [comment]
Talked a bit offline. This is related to the `accessibility-checker` package (not the accessibility-checker-extension package referenced). Their project had run yarn install earlier and checked in a lock file containing an older chromedriver. The `accessibility-checker` does not include its own lock file.

Due to the chromedriver issue mentioned in https://github.com/giggio/node-chromedriver/issues/451 , the `detect-chromedriver-version` mechanism was failing. 

This is remedied by clearing the project lock file and installing fresh to pull the latest chromedriver.

**Comment by davidmenendez** [comment]
thank you for clarifying everything
