### ISSUE TITLE
Firefox and Chrome extensions sometimes have different results?

### ISSUE THREAD

**Issue by carmacleod** [IBMa/equal-access#340]
Steps:
- Open the following page in both Chrome and Firefox (Win or Mac):
   - https://thepaciellogroup.github.io/aria-test-builder/dist/testcases/noscript-test.html
- Run Accessibility Checker in each browser (Assessment panel or Checker panel; Preview Rules or Latest)
- Compare the Chrome results with the Firefox results

The Chrome extension finds all of the role and attribute violations on the noscript elements, but the Firefox extension misses them entirely.

### Chrome/Win Accessibility Checker results (Preview Rules)
158 Violations

![image](https://user-images.githubusercontent.com/3331913/110487692-d2466300-80bb-11eb-8653-4809ce909033.png)

### FF/Win Accessibility Checker results (Preview Rules)
3 Violations

![image](https://user-images.githubusercontent.com/3331913/110487980-16396800-80bc-11eb-88ed-5568a252383a.png)

**Comment by tombrunet** [comment]
I'll leave this open to confirm, but the browsers do weird things with the noscript tag. I know this has come up before, but forget the details. My suspicion is that Firefox does not expose the noscript tag to the DOM since it's only relevant to content without scripts, and the DOM is irrelevant if scripts aren't running.

**Comment by carmacleod** [comment]
Ok, thanks @tombrunet - that makes sense.
Closing this issue.
