### ISSUE TITLE
Scan inside shadow-DOM

### ISSUE THREAD

**Issue by wkeese** [IBMa/equal-access#363]
### Summary

Make accessibility checker scan inside shadow DOM.

### Justification

Accessibility-checker won't find any errors inside of shadow DOM, which make it impossible to use https://github.com/carbon-design-system/carbon-web-components (and still have automatic checking for accessibility issues).

Since custom elements and shadow DOM are part of the HTML standard, they should be supported.

### Test case

```
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Test accessibility checker in shadow DOM</title>
</head>
<body>
<header>
	<h1>Test if accessibility checker flags label-less &lt;input&gt; inside shadow DOM</h1>
</header>
<main>
	<div id="container"></div>
	<script>
		var root = container.attachShadow( { mode: "open" } )
		var input = document.createElement("input")
		root.appendChild( input )
	</script>
</main>
</body>
</html>
```

**Comment by tombrunet** [comment]
https://github.com/IBMa/equal-access/pull/373 is work in progress. It seems to handle open shadow DOM okay on the surface. We'll need to iterate on this a bit since there are some rules that get confused about not being in a full-fledged document (e.g., the landmark rule thinks that content in a shadow DOM isn't within a landmark since it doesn't look outside the shadow hierarchy).

Not sure at the moment if we'll be able to handle closed shadow DOMs. It looks like Firefox provides a means for privileged access, but the Chrome discussions I found on first glance didn't appear to support it.

**Comment by wkeese** [comment]
Nice!  To be honest, I had to look up the [difference between closed and open shadow DOMS](https://stackoverflow.com/questions/39931284/what-is-the-difference-between-open-and-closed-shadow-dom-encapsulation-mode).   I see Carbon Web Components ([example](https://web-components.carbondesignsystem.com/?path=/story/components-button--default)) is using open shadow DOM, so I guess I don't really care about the closed case.

**Comment by tombrunet** [comment]
Did some more digging today, looking through the carbon webcomponent examples (https://web-components.carbondesignsystem.com/vue/index.html). Looks like this is going to be a bit more involved. Discoveries so far:
* node.ownerDocument within the shadowRoot of a web component returns the original doc, however, you need the fragment root in order to actually get element's by id. Need to identify a way to determine which approach we can use generally without a big performance hit.
* The browser is filling in the template slots under the covers, but presents them in the DOM in the original places. We may have to build some more smarts in to be able to generate the template to check correctly.

**Comment by tombrunet** [comment]
You should be able to scan shadow doms using the 'preview' archive/rule pack. I cleaned up several rules that didn't account the template / shadow dom structure, but I'm sure there are others. Please open other issues if you find them.

**Comment by wkeese** [comment]
Thanks!   I confirm it's handling the test case I left in this ticket.  It's not checking when `mode=closed` but I don't really care about that.

I will open tickets for other issues I see.
