### ISSUE TITLE
[Rules] revised allowed roles for <img alt=something>

### ISSUE THREAD

**Issue by scottaohara** [IBMa/equal-access#392]
an `<img>` with an accessible name `alt=something` (or `aria-label/labelledby`) should only allow a subset of ARIA roles to be applied.

[ARIA in HTML `img alt=something`](https://w3c.github.io/html-aria/#el-img)
[test case](https://thepaciellogroup.github.io/aria-test-builder/dist/testcases/img-test.html)

allowed roles:
`button`, `checkbox`, `link`, `menuitem`, `menuitemcheckbox`, `menuitemradio`, `option`, `progressbar`, `radio`, `scrollbar`, `separator`, `slider`, `switch`,`tab`or `treeitem`

DPub Role: `doc-cover`

**Comment by tombrunet** [comment]
@scottaohara Is the testcase up to date? We seem to agree with the testcase right now except for two cases:
* `radio` - The testcase says it's allowed, but the ARIA in HTML document doesn't list it, and it's not in your list above
* `img` - We often don't flag specifying explicit roles when they match the implicit role. Specifying it doesn't really have an effect in the accessibility tree since that's what it implicitly maps to anyway.

**Comment by scottaohara** [comment]
hi @tombrunet, 

per the first case, `radio` should be allowed and was missed during the original change to the image allowances.  I'm creating a PR to add that allowance back to the spec.  I will this issue to the PR I will be creating.

understood per your second point.  for instances like this one, it is more unnecessary than an error/warning.  For instances like `summary role=button`, which can actually cause, that's when ( i at least ) would expect conformance checkers to make sure that error was called out.

**Comment by tombrunet** [comment]
I suspect we may end up making a separate recommendation rule for cases of redundancy. Still discussing.

**Comment by tombrunet** [comment]
Just need to add 'radio' as allowable on this one.

**Comment by shunguoy** [comment]
merged to #721  close this one
