### ISSUE TITLE
Better document multi-URL options

### ISSUE THREAD

**Issue by mgifford** [IBMa/equal-access#425]
### Summary

I'd like to be able to easily scan a csv file of URLs, or a simple sitemap.xml or better yet just crawl a domain, while respecting the robots.txt file. 

### Justification

Others are already doing it with axe:
  https://github.com/MSU-NatSci/DomainAccessibilityAudit
  https://github.com/GovTechSG/purple-hats

Would be nice to have a comparison with equal access.

I do think that site-wide testing is important as I've stated here:
  https://www.smashingmagazine.com/2021/04/bake-layers-accessibility-testing-process/

Governments and other organizations are starting to do organization-wide monitoring as part of Europe's [Web Accessibility Directive](https://en.wikipedia.org/wiki/Web_Accessibility_Directive), and it really is a best practice that every organization should be able to do with convenient open source tools. 

### "Must have" functionality

This might already exist. Might just need to document how it is done. 

When I saw this article I thought you'd released something big for GAAD, but still don't see what is different:
  https://venturebeat.com/2021/05/17/ibm-upgrades-web-accessibility-tool-for-finding-and-fixing-issues/

Maybe I just a greater fleshed out definition of the batch configuration options required. There are a lot of assumptions built into the existing documentation. 
  https://developer.ibm.com/technologies/web-development/blogs/ibm-launches-equal-access-toolkit-developers-accessible-apps-and-websites/

I think I might just need a better example to get started. Ideally this would be in the documentation.

**Comment by tombrunet** [comment]
The changes mentioned are related to the browser extension - you can now log scans of several pages and then save the cumulative results when you are done. Before, you had to save every individual scan. The Node-based packages were already designed to be able to scan multiple pages.

The packages you mention are not part of Axe, but are simply projects using Axe engine. You can do the same with the Equal Access engine using the `accessibility-checker` package: https://www.npmjs.com/package/accessibility-checker . 

There are a few ways to go about what you're proposing. Perhaps the more straight-forward approach is to use the command-line tool included with the `accessibility-checker` package. 
```
Usage: achecker [flags] [command / file / directory / URL]
```
If you're trying to scan a list of URLs, you can put them in a .txt file, one per line, and point the command-line tool at that .txt file. It will then load each URL in the file with puppeteer and scan it.

Otherwise, you might be able to fork one of the above projects and swap out the calls to Axe with calls to the Accessibility Checker. In the first project you note, looks like there are three or four lines to setup the engine and call it, and then a function or two to process the results. We have had teams find crawlers that output a list of URLs and then feed them into the command-line tool above.

We have had general requests for this type of function, but when we dig into the details with the teams they usually end up needing something else and find some of the above mentioned solutions work for them. A lot of the web application teams don't get good coverage from crawlers due to various login and input issues. Some teams start out with separate function and accessibility tests and end up abandoning the accessibility - they're more successful when they blend those together. Some web-facing teams have started with crawlers and find that the crawler's coverage is spotty or disconnected from other quality checks they're doing and end up integrating the engine into their other QA processes. Overall, I will leave this issue open since it's something we want to keep in mind, but I don't think we're going to get to it in the near-term.

**Comment by marcjohlic** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Equal-Access-61ae71f9f8b4ec001e136462/issues/IBMa/equal-access/425?planning-poker) with ZenHub @aliunwala @drjoho @mbgower @philljenkins @shunguoy @tombrunet

**Comment by sct-will** [comment]
There have been updates to accessibility-checker/src/README.md to detail multi-scan options, but an update has been made to make this documentation a bit more obvious in the README by highlighting this in the features list and header text in PR https://github.com/IBMa/equal-access/pull/1230

**Comment by ErickRenteria** [comment]
Closing issue, information was provided on how to achieved the task and documentation was updated.
