### ISSUE TITLE
Automated tests ruleset and screenshots

### ISSUE THREAD

**Issue by sawhney-kartik** [IBMa/equal-access#635]
How can I find the rules that are used in automated tests specifically to identify violations (not potential violations)? The ruleset in the readme seems to be all of the rules including those for manual testing. Also, it seems that screenshot capture can be toggled on in the config, but that doesn't do anything for me. Where can I read more about it?

**Comment by tombrunet** [comment]
The rulesets specify whether or not a rule covers a violation or a recommendation. The individual rule logic determines if the issue is confidently detected, or needs manual review. Generally, we try to name the NLS messages based on the scenario, so you can get a sense from that file as to what each rule returns. I'm not aware of any cases at the moment where we changed the output type without changing the message id:
https://github.com/IBMa/equal-access/blob/master/accessibility-checker-engine/src/v2/checker/accessibility/nls/index.ts

Older rules return one or the other since this was not supported in the older engine. Some newer rules, such as `WCAG20_Html_HasLang` include both failures and potentials since it depends on the scenario as to how confident the rule can be.

**Comment by sawhney-kartik** [comment]
Thanks, this is very helpful. Any thoughts on the screenshot? How can I use the capture_screenshots option defined in the config, and does it specifically highlight the violation or simply captures the webpage screenshot?

**Comment by tombrunet** [comment]
Sorry - thought you were asking about the browser extension, but looks like you're asking about the automated tool? We are not currently saving the screenshots in the automated tools. There was a 'reporter' that would send these to a server, but that's not enabled at the moment.

If you look at this file: 
https://github.com/IBMa/equal-access/blob/dac6cd2e2a7914f3742760466918328facf27059/accessibility-checker/src-ts/lib/ACHelper.ts

and search for `captureScreenshots`, you'll see how to do it for Selenium and Puppeteer. We don't currently have the function enabled on the reporters to save those anywhere.

**Comment by sawhney-kartik** [comment]
Sounds good, thank you
