### ISSUE TITLE
[BUG]: The version number is adding 999 at the end of the number in the manifest 

### ISSUE THREAD

**Issue by eirckr** [IBMa/equal-access#753]
### Project

a11y checker extension

### Browser

Chrome

### Description

Build: https://github.com/IBMa/equal-access/actions/runs/2007472974
The manifest has an extra 999 to the version. This is for both browsers please review attachments 

`{
	"manifest_version": 2,
	"name": "IBM Equal Access Accessibility Checker",
	"description": "A web browser extension for checking accessibility issues",
	"author": "IBM",
	"version": "3.1.23.9999","version_name": "3.1.23",
    "homepage_url": "https://ibm.com/able",
	"icons": {
        "16": "assets/Bee_Logo@16px.png",`

<img width="750" alt="Screen Shot 2022-03-18 at 11 19 32 PM" src="https://user-images.githubusercontent.com/62436670/159126561-0d38f920-e2de-4dd4-8338-23e9efb19547.png">
<img width="243" alt="Screen Shot 2022-03-18 at 11 25 18 PM" src="https://user-images.githubusercontent.com/62436670/159126563-5bba236e-ceb8-44c9-855b-e569d2c32bba.png">

### Steps to reproduce

Install and launch the extension.

**Comment by tombrunet** [comment]
The version number is by design. Release candidates would be like 3.1.4.0, 3.1.4.1, etc, so the release has to be 3.1.4.9999. The version_name is supposed to be a field that is the displayed version, but it seems Chrome isn't recognizing it even though it's advertised as a valid field. I'll have to look at how the version number is displayed, but it's technically correct.
